a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços?',a.isspace())
print('Esta capitalizado?',a.isupper())
print('É um numero?',a.isnumeric())
print('Esta em letras maiusculas?',a.isalnum())
print('Esta em letras Alfabetico?',a.isalpha())
print('É alfanumerico?',a.isalnum())
print('Esta em letras minusculas?',a.islower())
print('Esta capitalizado?',a.istitle()) 